"use client";
import { useState } from "react";
import { MOCK_PR } from "@/lib/mock-repo";
import styles from "./panels.module.css";

export default function TranslatorPanel() {
  const [mode, setMode] = useState<"technical" | "executive">("executive");
  const [step, setStep] = useState<"idle" | "translating" | "result">("idle");
  const [progress, setProgress] = useState(0);

  const handleTranslate = () => {
    setStep("translating");
    setProgress(0);
    let p = 0;
    const iv = setInterval(() => {
      p += Math.random() * 20 + 10;
      if (p >= 100) {
        p = 100;
        clearInterval(iv);
        setTimeout(() => setStep("result"), 300);
      }
      setProgress(Math.min(p, 100));
    }, 160);
  };

  return (
    <div className={styles.panelGrid2}>
      {/* ── LEFT: PR Input ─────────────────────────────────── */}
      <div>
        <div className={styles.sectionLabel}>📋 Pull Request Description (Technical)</div>
        <div className={`glass-card ${styles.prCard}`}>
          <div className={styles.prHeader}>
            <span className="badge badge-purple">PR #251 — Merged</span>
            <span style={{ fontSize: 12, color: "var(--text-muted)" }}>2 hours ago · by Farid Hashimli</span>
          </div>
          <pre className={styles.prBody}>{MOCK_PR.technical}</pre>
        </div>

        {step === "idle" && (
          <button id="btn-translate" className="btn btn-primary" style={{ marginTop: 16, width: "100%" }} onClick={handleTranslate}>
            👔 Translate for Executives
          </button>
        )}
        {step === "translating" && (
          <div style={{ marginTop: 16 }}>
            <div className={styles.analyzingLabel}>Bob 360 translating technical jargon...</div>
            <div className="progress-bar" style={{ marginTop: 8 }}>
              <div className="progress-fill blue" style={{ width: `${progress}%` }} />
            </div>
            <div className={styles.analyzingHint} style={{ marginTop: 6 }}>
              Identifying business impact · Removing jargon · Summarizing for C-suite...
            </div>
          </div>
        )}
      </div>

      {/* ── RIGHT: Executive Output ────────────────────────── */}
      <div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div className={styles.sectionLabel}>🤖 Bob 360 — {mode === "executive" ? "Executive Summary" : "Technical View"}</div>
          {step === "result" && (
            <div className={styles.modeToggle}>
              <button
                className={`${styles.modeBtn} ${mode === "technical" ? styles.modeBtnActive : ""}`}
                onClick={() => setMode("technical")}
              >Technical</button>
              <button
                className={`${styles.modeBtn} ${mode === "executive" ? styles.modeBtnActive : ""}`}
                onClick={() => setMode("executive")}
              >Executive</button>
            </div>
          )}
        </div>

        {(step === "idle" || step === "translating") && (
          <div className={`${styles.emptyState} glass-card`}>
            <div className={styles.emptyStateIcon}>👔</div>
            <div className={styles.emptyStateText}>
              {step === "idle"
                ? "Bob 360 will convert your technical PR into a clear, jargon-free executive report."
                : "Extracting business value, performance metrics, and user impact..."}
            </div>
          </div>
        )}

        {step === "result" && (
          <div className={styles.resultContainer}>
            {mode === "executive" ? (
              <>
                {/* Executive Report */}
                <div className={`${styles.executiveReport} glass-card`}>
                  <div className={styles.reportHeader}>
                    <span style={{ fontSize: 20 }}>📊</span>
                    <div>
                      <div style={{ fontWeight: 700, fontSize: 16 }}>Release Update — May 14, 2026</div>
                      <div style={{ fontSize: 12, color: "var(--text-muted)" }}>Generated by Bob 360 · PR #251</div>
                    </div>
                  </div>

                  <div className={styles.reportHeadline}>{MOCK_PR.executive.headline}</div>

                  <ul className={styles.reportBullets}>
                    {MOCK_PR.executive.bullets.map((b, i) => (
                      <li key={i} className={styles.reportBullet}>
                        <span style={{ color: "var(--accent-green)", marginRight: 8 }}>✓</span>
                        <span dangerouslySetInnerHTML={{ __html: b.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>") }} />
                      </li>
                    ))}
                  </ul>

                  <div className={styles.reportImpact}>
                    <div style={{ fontWeight: 600, marginBottom: 6, color: "var(--accent-cyan)" }}>💼 Business Impact</div>
                    <div style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>
                      {MOCK_PR.executive.impact}
                    </div>
                  </div>

                  <div className={styles.reportDebt}>
                    <span className="badge badge-green">✓ {MOCK_PR.executive.technicalDebt}</span>
                  </div>
                </div>

                <button
                  id="btn-export-pdf"
                  className="btn btn-ghost"
                  style={{ width: "100%", marginTop: 12 }}
                >
                  📥 Export as PDF
                </button>
              </>
            ) : (
              <div className={`glass-card ${styles.prCard}`}>
                <div className={styles.prHeader}>
                  <span className="badge badge-purple">Original — Technical</span>
                </div>
                <pre className={styles.prBody}>{MOCK_PR.technical}</pre>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
